Update to 1.19.2
alcatrazEscapee/hexlands pull request #7
Opened 2023-01-22 21:27 UTC by Patbox

This pr updates this mod to 1.19.2. It isn't compatible with 1.19.3 (blame Mojang), as it is something for next one.

Main changes:
- Moved generator type definition to json
- No longer changes default one. It should be left to modpack datapacks to do so (it's tag based now)
- Replaced RandomState patching to not use cache and instead just check agains a boolean

2023-01-22 23:46 UTC, alcatrazEscapee requested changes

2023-01-22 23:46 UTC, alcatrazEscapee commented on Common/src/main/java/com/alcatrazescapee/hexlands/world/HexRandomState.java
> -    private static final Cache<RandomState, HexRandomState> RANDOM_STATE_EXTENSIONS = CacheBuilder.newBuilder()
Why the change from a cache to relying on a mixin?

2023-01-22 23:46 UTC, alcatrazEscapee commented on Common/src/main/java/com/alcatrazescapee/hexlands/world/HexRandomState.java
> -    public static HexRandomState modify(RandomState state, NoiseGeneratorSettings settings, HexSettings hexSettings)
My intuition says this method needs to be synchronized on the `RandomState`, no?

2023-01-22 23:46 UTC, alcatrazEscapee commented on Common/src/main/java/com/alcatrazescapee/hexlands/util/HexSettings.java
> +        DEFAULTS.put(new ResourceLocation("the_end"), END);
These should be in the hexlands namespace, not minecraft.

2023-01-22 23:46 UTC, alcatrazEscapee commented on Common/src/main/java/com/alcatrazescapee/hexlands/util/HexSettings.java
> +    public static final Codec<HexSettings> CODEC = Codec.either(ResourceLocation.CODEC, OBJECT_CODEC).xmap(x -> x.map(s -> HexSettings.DEFAULTS.getOrDefault(s, OVERWORLD), s -> s), x -> Either.right(
`.xmap(.. getOrDefault)` is incorrect as it will consume errors. It should use `.comapFlatMap` and do a null check -> `DataResult.error()`

2023-01-23 06:13 UTC, Patbox commented on Common/src/main/java/com/alcatrazescapee/hexlands/world/HexRandomState.java
> -    private static final Cache<RandomState, HexRandomState> RANDOM_STATE_EXTENSIONS = CacheBuilder.newBuilder()
Since it already just patched RandomState, effect is the same and usage of cache felt like overkill

2023-01-23 06:21 UTC, Patbox commented on Common/src/main/java/com/alcatrazescapee/hexlands/world/HexRandomState.java
> -    public static HexRandomState modify(RandomState state, NoiseGeneratorSettings settings, HexSettings hexSettings)
Tbf, might be good to put it for patching code  (just in case), but otherwise it shouldn't matter much since it only changes fields, not more volatile structs (worst case it gets patched twice, which doesn't change anything)

2023-01-23 06:22 UTC, Patbox commented on Common/src/main/java/com/alcatrazescapee/hexlands/util/HexSettings.java
> +        DEFAULTS.put(new ResourceLocation("the_end"), END);
These are just config "templates" referring to vanilla dimensions so I think they don't matter here.

2023-01-23 22:48 UTC, alcatrazEscapee commented
https://github.com/alcatrazEscapee/hexlands/commit/97c9f2243a466a7b12ea019c18e0865ed03ebc41

2023-01-23 22:48 UTC, closed without merging