Update to 1.19.3
alcatrazEscapee/hexlands pull request #9
Opened 2023-01-22 22:43 UTC by Patbox

Follow up to https://github.com/alcatrazEscapee/hexlands/pull/7

As stated before, it isn't compatible with 1.19.2.

This one would be fine as "main" 1.19.x branch I guess

2023-01-22 23:46 UTC, alcatrazEscapee requested changes

2023-01-22 23:46 UTC, alcatrazEscapee commented on Common/src/main/java/com/alcatrazescapee/hexlands/package-info.java
> -import javax.annotation.ParametersAreNonnullByDefault;
Why?

2023-01-22 23:46 UTC, alcatrazEscapee commented on Common/src/main/java/com/alcatrazescapee/hexlands/world/HexChunkGenerator.java
> +    public int getBaseHeight(int $$0, int $$1, Heightmap.Types $$2, LevelHeightAccessor $$3, RandomState state)
Parameter names??

2023-01-22 23:46 UTC, alcatrazEscapee commented on Fabric/src/main/java/com/alcatrazescapee/hexlands/platform/FabricPlatform.java
> +        }
wtf is this? And why on earth is `e.printStackTrace()` acceptable error handling?

2023-01-23 06:24 UTC, Patbox commented on Common/src/main/java/com/alcatrazescapee/hexlands/package-info.java
> -import javax.annotation.ParametersAreNonnullByDefault;
It complained about them missing, making it not compile

2023-01-23 06:24 UTC, Patbox commented on Common/src/main/java/com/alcatrazescapee/hexlands/world/HexChunkGenerator.java
> +    public int getBaseHeight(int $$0, int $$1, Heightmap.Types $$2, LevelHeightAccessor $$3, RandomState state)
Yeah will add these, didn't think much about it as it's just passthrough outside of patching state

2023-01-23 06:26 UTC, Patbox commented on Fabric/src/main/java/com/alcatrazescapee/hexlands/platform/FabricPlatform.java
> +        }
For some weird reason, it just crashed without it (Fabric APi bug likely). it's only try-catched since it's internal implementation, which might be gone once it's fixed (logs here would just indicate it's safe to remove)

2023-01-24 01:01 UTC, closed without merging